export const INIT_ADMIN_DASHBOARD_CATEGORIES = 'INIT_ADMIN_DASHBOARD_CATEGORIES';
export const ADD_ADMIN_DASHBOARD_CATEGORY = 'ADD_ADMIN_DASHBOARD_CATEGORY';
export const REMOVE_ADMIN_DASHBOARD_CATEGORY = 'REMOVE_ADMIN_DASHBOARD_CATEGORY';