export const INIT_ADMIN_DASHBOARD_CATEGORIES = 'INIT_ADMIN_DASHBOARD_CATEGORIES';
export const ADD_ADMIN_DASHBOARD_CATEGORY = 'ADD_ADMIN_DASHBOARD_CATEGORY';
export const REMOVE_ADMIN_DASHBOARD_CATEGORY = 'REMOVE_ADMIN_DASHBOARD_CATEGORY';

export const INIT_ADMIN_RESOURCE_SITES = 'INIT_ADMIN_RESOURCE_SITES';
export const ADD_ADMIN_RESOURCE_SITE = 'ADD_ADMIN_RESOURCE_SITE';
export const REMOVE_ADMIN_RESOURCE_SITE = 'REMOVE_ADMIN_RESOURCE_SITE';